# The chance essence will drop from a mob. 1 of drop-chance mobs will drop essence. Four essence
# are required to make an egg, so essentially an egg is attained 1 of (4 * drop-chance) mobs killed.
drop-chance: 256